template: |
  ## Changelog

  {{CHANGELOG}}
  
categories:
  - title: "ğŸš€ feature"
    labels:
      - "enhancement"
  - title: "ğŸ› Bug Fixes"
    labels:
      - "fix"
  - title: "ğŸ§¹ Maintenance"
    labels:
      - "chore"
  - title: "ğŸ“ Documentation"
    labels:
      - "docs"
